### ISSUE TITLE
Peer to Peer Code Review: Team The Aries

### ISSUE THREAD

**Issue by kubilaycaglayan** [kevinfrontend/newsweek-clone#2]
Hello Kevin,
Thanks for your extra effort about presentation. That was inspiring.
Things can be improved:

1. Missing navigation at header
2. Newsweek logo off-center
3. Readme refresh
4. Live demo link should be refreshed
5. Commented out codes should be removed
6. Api related content is not visible on some screens

With all our respects...

**Comment by kevcap** [comment]
Thanks! I'll surely improve those changes, thanks for your advices!
